### ISSUE TITLE
Add ??? / AnyValue

### ISSUE THREAD

**Issue by krzkaczor** [ts-essentials/ts-essentials#134]
## Motivation

Often during rapid prototyping phase when I dont need full type correctness (or I cant provide it JUST yet). I want to just put any value and execute code without worring about typescript errors. These days i use often something like `null as any` as it's fast to type. We can standarise it a little bit and make it part of `ts-essentials`. 

Note: it's basically `any` counterpart on the value level.

Scala has quite useful [???](https://alvinalexander.com/scala/what-does-three-question-marks-in-scala-mean) operator. 

## Implementation

We can implement it in TypeScript simply as:

```
const ANY = undefined as any;
```

UNFORTUNATELY, `???` is not a valid symbol in JS :( Other possible names: `AnyValue`, `Anything`. I quite like `ANY` as it's short. 

It would be perfect to implement it in a way that interaction with this value triggers a runtime error but i think it's not possible (es6 proxy but on primitive value?)

If you have any other ideas let me know.

**Comment by quezak** [comment]
would it be just an exported named constant then? imho it should have a name that clearly shows it shouldn't be there in the long run, like `NOT_IMPLEMENTED`, `VALUE_TBD`, `UNKNOWN_YET` or something. `ANY` is imho too short and confusing with the `any` type, also a simple name would encourage people to use this in regular code, while it should be only temporary.

**Comment by krzkaczor** [comment]
So we need two things: any value and any function they purpose is to silent compiler and *maybe* fail during runtime.

Let's discuss naming. Do we want to go to with all UPPERCASE? (I think you are pro this idea @quezak ), I guess it makes sense but I just realized that we didnt do `NOOP` uppercased (which should be fixed)... Also, I strongly believe that these names should be as short as possible.

```typescript
export const ANY = undefined as any;
export const NOT_IMPL = (): any => { throw new Error("Unimplemented yet") }
```

Other names:
`ANY` => `ANY_VAL`
`NOT_IMPL` => `UNIMPL`, `UNIMPLEMENTED` (too long IMO 😢 )

Let's do a brainstorming session 😆 @quezak @macbem

**Comment by quezak** [comment]
> Let's discuss naming

A nope from me on naming functions in `CAPS` -- this is reserved for "constants" (understood in the traditional C-like sense, not just `const` instead of `var`). Functions are functions, should still be named in `camelCase`.

IMO `ANY` is too vague / confusable with `any`, `ANY_VAL` is ok.
`unimplemented` is not too long, it could even be `unimplementedFnStub`, I'm sure @macbem will come up with even longer ideas :D

**Comment by macbem** [comment]
IMO, `ANY_VAL` and `notImpl` are good choices. I agree with @quezak - `ANY` is too similar to `any`.

`notImpl` naming proposals:
- `missingImpl`
- `todoImpl`
- `todo`
- `unimpl` -- this one is kinda unreadable when lowercased imo
- `throwOnCall` - describes what it does exactly

**Comment by krzkaczor** [comment]
In my mind, this is a "do not try this at home" kinda type. Only as a temporary solution when prototyping code. For folks that know what they're doing.

I still find uses for something like this (i just write `null as any` 😆 ) but I won't push it too hard. 
As for the name I think `todo` (for unimplemented function) and `todoVal` (for `any` val) seems like a good names.

**Comment by Beraliv** [comment]
@krzkaczor is it still valuable for you? I can include it as a part of v10.1 release plan

**Comment by krzkaczor** [comment]
I don't think so :) I am gonna close this one.
