### ISSUE TITLE
Consider support of `exactOptionalPropertyTypes` flag

### ISSUE THREAD

**Issue by Beraliv** [ts-essentials/ts-essentials#233]
Here it's about the difference of `{ a: undefined }` and `{}`

I'm not sure if we need to do anything here, but there can be issues regarding setting or not this flag in the future

Issue for `strictOptionalProperties` – https://github.com/microsoft/TypeScript/issues/44604
It's now named as `exactOptionalPropertyTypes` – https://github.com/microsoft/TypeScript/pull/44626

**Comment by Kay-Yuan** [comment]
Hi, I tried `exactOptionalPropertyTypes` flag on my Angular project. It works fine in my .ts file. The optional property type is `type-example` only without `undefined`. But the .html file still showed the optional property type as `type-example | undefined`. Do you guys have any idea about this? Any feedback would be appreciated.

**Comment by Beraliv** [comment]
I will close it for now as it's stale and no one reported bugs about it
