### ISSUE TITLE
[question/doc] RequiredKeys confusion

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#309]
I'm confused about why I'm getting `never`, `  _skipKeys: RequiredKeys<T>[]` by itself seems to reproduce it where a `string` is not assignable to `never`

```
Type 'MarkRequired<Partial<MaybeUnifiedUserCommentOutputDto>, never>[]' is not assignable to type 'MaybeUnifiedUserCommentOutputDto[]'.
  Type 'MarkRequired<Partial<MaybeUnifiedUserCommentOutputDto>, never>' is not assignable to type 'MaybeUnifiedUserCommentOutputDto'.
    Type 'MarkRequired<Partial<MaybeUnifiedUserCommentOutputDto>, never>' is not assignable to type 'Omit<UnifiedUserCommentInputDto, "eid">'.
      Property 'message' is optional in type 'MarkRequired<Partial<MaybeUnifiedUserCommentOutputDto>, never>' but required in type 'Omit<UnifiedUserCommentInputDto, "eid">'.
```

```ts
export declare function stripUndefined<T>(
  object: T,
  validator: Joi.AnySchema,
  _skipKeys: RequiredKeys<T>[]
): MarkRequired<Partial<T>, RequiredKeys<T>>

export type UnifiedCommentInputDto = {
  message: string
  type: UnfiedCommentType
}

export interface UnifiedCommentOutputDto extends UnifiedCommentInputDto {
  id: string
  timestamp: Date
}

export type MaybeUnifiedUserCommentOutputDto = MarkOptional<UnifiedUserCommentInputDto, 'eid'> & UnifiedCommentOutputDto

stripUndefined(comment, unifiedCommentOutputDtoValidator, ['message', 'id', 'type'])
```

doesn't look like `message` etc is optional to me

**Comment by Beraliv** [comment]
Hey @xenoterracide!

Thank you for your time and raised issue!

Can I ask you quickly create the reproduction in [TypeScript Playground](https://www.typescriptlang.org/play) please? I cannot check it now because it's not clear what `Joi.AnySchema`, `cleanDeep`, `validateWith`, `UnfiedCommentType`, `UnifiedUserCommentInputDto`, etc

I started it here, could you please add rest parts so it will be clear what happens? https://tsplay.dev/wEvBkN

Thank you in advance and I'm waiting for the other details!

**Comment by Beraliv** [comment]
I dug into type details and found the following:

if I rewrite your function as `foo` (please check Playground – https://tsplay.dev/mZGXEW), you will see that your function returns the object of the same type

If you want to get rid of required keys by passing the list of it, you need to update your function:

```diff
- declare const foo: <T>(obj: T, keys: RequiredKeys<T>[]) => MarkRequired<Partial<T>, RequiredKeys<T>>;
+ declare const foo: <T, U extends RequiredKeys<T>>(obj: T, keys: U[]) => MarkRequired<Partial<T>, U>;
```

This way your keys will be inferred differently depending on what you pass – https://tsplay.dev/Ndor0w

Does it sound like what you wanted to achieve? If not, please let me know what needs to be done

**Comment by xenoterracide** [comment]
hmm... is there a functional difference between yours and mine? looks the same... let's see if I can update the playground with the problem I'm encountering. Realistically what I'd really love is to use the `RequiredKeys` fields that are passed to `U` rather than just `RequiredKeys` in general

```ts
export function stripUndefined<T, U extends RequiredKeys<T>>(
  object: T,
  validator: Joi.AnySchema,
  _skipKeys: ReadonlyArray<U>
): MarkRequired<Partial<T>, U> {
  const clean = cleanDeep(object, {
    nullValues: false,
    emptyArrays: false,
    emptyObjects: false,
    emptyStrings: false,
    NaNValues: true,
  })
  return validateWith(clean, validator, { stripUnknown: true })
}
```

**Comment by xenoterracide** [comment]
[tsplay](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQM6oKawCpQK4ZwCGqK6WMANHAJKoCiAHkQMbwC+cAZlBCHACIWEAHYATYDGCiiAGwC0MAJ5gM8lgAsMLANaoBAbgBQoSLERwAShgCOeYFAxiA0hiWpqAWSJQd1uw5OXj46APJgUjKycJw8fHAA5DCo8hjkIlJyqAnGRhiMZvAYInj8AKoiXMBOAMJ8IMUw2CqECEZwcGUAyvSWcAC8iXiYUAmU7XBdAJpd2PSeA4mo7jAYIGNG7EZ5BdDwyqqdIsBVtfWNNCJgeDAAIjAQi20dDehEAOYYAFxwqDBQwBE7wmB2+R1OYjqIAaGWaqk223yhTggNWUC4rEIFRO1Uh5wyoRu1zuDzg+VW4lI2IhUJhMEuxPuj2eKLEPz+AKBINAaRgRHAP1uRFWCJ2yNRWAxLCxxwhZRGtIuVxuTLJjApYipstxioyDJVpJZGGAbN+-0BwI6wigjlQkHEFq6fNWAH52eauR0+e9PmJ5VhUG6zZz3gBtAC6EyIYDAvAAblhsJJZBggxyLaKkXs4KCjjinP6oLqYISYIzSYNqTr8fTlSTHgAyPM0mul8sQMXZ3PeJQAIwwVYLCpr+vri28vnCkREcgAPIO-cPoUr29QEsaxAkAHyd8zdoh9gfaodYYttg2PQYTsIRaQz2Tz4+L08jutMtcb7dwJsLs9Ei-bLu8BiNosg+IQXB4CIbB3sGwBgBUIFVCITiztg1BlGqGqkP49iOC4bioGhW5bgAFBMEC9gAVtoMA-OhEwAPqoDo8GuO4PzWEQYiiLISjIDaB7zjuACUPzXrhgRiLOAAKPiZA+2BbhhO5GCQSjQdwUEwaIcCfDAxaoKRYlwDJvAgMAmCzj2-YLoWf5lheEZbogEyODAeBQCIcChgg7DhgAdCA0akaRtrUMAIkDC5LJWqIfxwMIy4ZOJB62U+9mtv+Y6DLFHRwK8qAfGCCREBs+X5dGsYQAmUBJjAKY-AkvblRViXQLa9oSECTrCiVLCtRVJpNZu4xtWSw2JBgg35aCPwVC2yVNC0AXdL0Y1tVIrx8gKcAoQA7nAQqrMZG0Vd6vqFqgTVEJQLUBXasiSKRYwJCJZ0xNsFXuZ53npgh4gYMhTikUldLUKGCSFcVYyJCasNJC0CThiJEzsKj7BAA)

**Comment by xenoterracide** [comment]
updated link, cleaned up, not sure how you get that shortened url [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQM6oKawCpQK4ZwCGqK6WMANHAJKoCiAHkQMbwC+cAZlBCHACIWEAHYATYDGCiiAGwC0MAJ5gM8lgAsMLANaoBAbgBQoSLERwAShgCOeYFAxiA0hiWpqAWSJQd1uw5OXj46APJgUjKycJw8fHAA5DCo8hjkIlJyqAnGRhiMZvAYInj8AMJ8IMUw2CqECEZwcACqAMr0lnAAvIl4mFAJlI1wrQCardj0nt2JqO4wGCCDRuxGeQXQ8MqqcBUgVRk0ImB4MAAiMBAzDU1V6EQA5hgAXHCoMFDAIg-D2y+7lWqtVUKzW+UKcC+CygXFYhD2BxgoVOJ3Olzg+QW4lICOqR1RFyuN0hYle70+31+oDSMCI4FeZyIC1B6whUKwsJYhGaImAXGATma-Vxh2Op0JGMYWLEOMBooJ6OJGGApLeHy+PyatIeTzEQqwqAA-GT1d8ANoAXRZ4M2cD+LV5-MFwrlSJR4vRPRFMHxHquADIAftqsiYAqIKzbfbvEoAEYYfVQb2+tFXHreXzhSIiOQAHh5fIFepdwflfuoCWVYgSAD5I+Zo0Q4wmS4jQ+GZhmwhFpDnZPnHUXE8mxamK1Xa3BA972361vX4GJtLIfIQuHgRGxe2rPmAeUv+SInLnsNRmpLpaR-PZHC43KgTzWawAKYYQWMAK20MFep+GAH1UB0YAwFcdxXmsIgxFEWQlGQKAoCbfM6wASleLtr0CMRcwABR8TJ+2wGszzrIwSCUTduA3LdRDgJ4YG9VBnzQuAcN4EBgEwXMY3jYdXVnVNLRrRBhkcGA8CgEQ4DNBB2AtAA6EAiDAZ9n0cDxIRQ7phOJJphBEd44GEUsfzgHiWywGd3VTa5hiaW40lQR5-gSIhlns+yVVeBJqyGDymirbyMHc-y-leb1gQweS2g6PzQupd46TAV4jwAdzgRkFmYuKPO1XVE1QbyiEoWMEnk1AwFkSRn0GBIUJymI1g8sSJKk8kQP3DBDycZ9jMRagzQSO4nKeQZEhVMakjqBILRQ4Z2Dm9ggA)

**Comment by xenoterracide** [comment]
I saw that, around the same time you posted, and yet my build still doesn't work, although intellij seems to think it should... hmm... checking further...

**Comment by xenoterracide** [comment]
I wonder if it somehow has to do with the `typescript-strict-plugin` ... because this is compiling, but not locally when `tsc-strict` is run [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgQQM6oKawCpQK4ZwCGqK6WMANHAJKoCiAHkQMbwC+cAZlBCHACIWEAHYATYDGCiiAGwC0MAJ5gM8lgAsMLANaoBAbgBQoSLERwAShgCOeYFAxiA0hiWpqAWSJQd1uw5OXj46APJgUjKycJw8fHAA5DCo8hjkIlJyqAnGRhiMZvBi2rI+hFx4ImzSInCoMFDAYACq4hhcwCJOADzY1M1w+TAY4qT+9o4ubqi9AHyzABRGcHAQAEYAVtowAFxwfctwAPqoOk2u7nvWRGKiskrIUFBESt3Ns0YAlHvevuOBYm6AAUfJlZHN+h88gVoPBOsMoFxWIQAMJ8EAjGAoxxEYahPAwMAEgAiMAgiEOwhAGIyNDEe3qjREAHNKTjhmJsKA0jAiOA9sTcRgjOwjNDCnB4VgkSxUejMdiMELSeSEJT5RlsCoMAyGp1WSsMegiMydXU9SyRWLiixSo5uJVqqI4KaYAt1hs9kg1hAxEo9kQREoYt8gbwQMBMN1vb7-cQgzFZnAxSQlFUHVVIrUWOyMGjqZilitHHYeXt8zSsbmVZQvnsw3xIxhuhWFbn8YSSWSk2qVsIRPULD6-TEvXBh3HWxlFUKO0SYCqYnAALzEADuREkLowbt7K3Hsd1jRabQ6XTECxLBHq1AA2gkjagTRgEtQElTK1rVAkALqfWsrOwnyHI4MB4FAtQTiKQA)

**Comment by xenoterracide** [comment]
intellij is telling me the returned signature looks something like this

```ts
export function stripUndefined<ServiceNowMaybeUserCommentCreateDto, "message" | "commentType">(     object: ServiceNowMaybeUserCommentCreateDto,     validator: Joi.AnySchema<...>,     _skipKeys: readonly ("message" | "commentType")[]): MarkRequired<...>
```

but compilation is telling me

```
src/services/comment/comment-service.ts:37:82 - error TS2322: Type 'string' is not assignable to type 'never'.

37     body: stripUndefined(request, serviceNowMaybeUserCommentCreateDtoValidator, ['message', 'commentType']),
                                                                                    ~~~~~~~~~

src/services/comment/comment-service.ts:37:93 - error TS2322: Type 'string' is not assignable to type 'never'.

37     body: stripUndefined(request, serviceNowMaybeUserCommentCreateDtoValidator, ['message', 'commentType']),
                                                                                               ~~~~~~~~~~~~~
```

```
export interface ServiceNowCommentCreateOutputDto {
  commentId: UnifiedExceptionId
  createdTimestamp: Date
}
```
it's not the `typescript-strict-plugin` only other thing that comes to mind is the fact that these are spread across 3 different workspaces.

**Comment by xenoterracide** [comment]
oops, just realized I pasted the wrong interface

```ts
export interface ServiceNowMaybeUserCommentCreateDto {
    message: string;
    commentType: UnfiedCommentType;
    userEid?: string;
    correspondingState?: string;
    taggedUsers?: string;
    approverTitle?: string;
}
```

**Comment by xenoterracide** [comment]
it errors like it can't even see the `RequiredKeys` in that module...

**Comment by xenoterracide** [comment]
but this works... 

```ts
export function stripUndefined<T, K extends keyof T>(
  object: T,
  validator: Joi.AnySchema,
  _skipKeys: ReadonlyArray<K>
): MarkRequired<Partial<T>, K> {
```

I don't get it at all

**Comment by Beraliv** [comment]
What typescript version do you use? Is it 4.6.2?

**Comment by xenoterracide** [comment]
No, we're on 4.3.5 (some front end library is keeping us there apparently). However I did try to switch to that in the TS playground or whatever and No problem happened. It's super weird... Maybe I should copy and paste all of the code into a single module and see if it still happens in our code base. It does kind of feel like it's because of the cross modules shenanigans...

**Comment by Beraliv** [comment]
Maybe that's the reason why it happens

Is there anything I can do here to help you?

If not, please feel free to close the issue!

**Comment by xenoterracide** [comment]
I don't know I gave up on it 😂. I thought maybe you had an idea.
