### ISSUE TITLE
StrictPick and StrictOmit

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#311]
I know there's `DeepPick` and `DeepOmit` but it feels like `StrictPick` and `StrictOmit` would make sense as simpler than those, and complementary to the other types already provided.

**Comment by xenoterracide** [comment]
I know me, I probably won't 😢. I had no idea that Pick was strict already. Perhaps in the documentation you could add StrictPick, And then in it simply say that pick is already strict, and you can just use that, as more of an educational bit For people like me that go looking for it.

**Comment by Beraliv** [comment]
> And then in it simply say that pick is already strict, and you can just use that, as more of an educational bit

I will think about it and will try to update the documentation respectively!

**Comment by Beraliv** [comment]
I've mentioned `Pick` in README – https://github.com/ts-essentials/ts-essentials/pull/330

The difference between `Omit` and `StrictOmit` was already there – https://github.com/ts-essentials/ts-essentials#comparison-between-omit-and-strictomit

**Comment by xenoterracide** [comment]
Cool, thanks. Then dumb people like me don't wonder why it's not there 😉

**Comment by xenoterracide** [comment]
I'll let you close, not sure if your process is on merge, or if it's on release

**Comment by Beraliv** [comment]
I will include it in the release so it will be clearer how it's connected

**Comment by Beraliv** [comment]
Merged to master branch, will close it (don't need the release)
