### ISSUE TITLE
create "enum like" type from  value of tuple

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#314]
is it possible to do some kind extraction of the values of tuples?

e.g

```ts
export const errorCodes: Required<SafeDictionary<[number, string], ErrorCodeKey>> = {
  unknownJoi: [200000, 'Request validation error'],
  notFound: [200001, 'Requested resource not found'],
  badRequest: [200002, 'An error has occurred'],
}
```

I could get, this without typing it out

```ts
type ErrorCode = 200000 | 200001 | 200002
type ErrorMessage = 'Request validation error' | 'Requested resource not found' | 'An error has occurred'
```
So I could make this type

```ts
export interface ErrorResponse {
  readonly id: ErrorCode
  readonly developerText: string // joi, etc, message
  readonly message: ErrorMessage
}
```

**Comment by Beraliv** [comment]
Hey @xenoterracide!

As I've mentioned in https://github.com/ts-essentials/ts-essentials/issues/313, you can create utility function `createFactoryWithConstrain` which can help you infer keys, but not values

It doesn't infer values because it's not readonly

To make it accept readonly object, you can add `Readonly` type first – https://tsplay.dev/wep8aW

As you see, it doesn't really change anything (it's still number and string respectively), but now you can use `as const` to get literal strings and numbers

1. You can use `as const` to make it string literal type and number literal type – https://tsplay.dev/WGVdXm
2. To make it shorter, just use `as const` for the whole object – https://tsplay.dev/wgZ8BW

Hope it helps!

Have a wonderful evening!

**Comment by xenoterracide** [comment]
ok, so I have this

```ts
import { SafeDictionary } from 'ts-essentials'

import { createFactoryWithConstraint } from './util'

type ErrorCodeTuple = Readonly<[number, string?]>

export type ErrorCodeIndex = { [k: string]: ErrorCodeTuple }
type ErrorCodes = Readonly<Required<SafeDictionary<ErrorCodeTuple, string>>>

const createErrorCodes = createFactoryWithConstraint<ErrorCodes>()

export const errorCodes = createErrorCodes({
  limit: [100023],
  UnifiedComment: [100091],
  UserInfo: [100092],
  unknownJoi: [200000, 'Request validation error'],
  notFound: [200001, 'Requested resource not found'],
  badRequest: [200002, 'An error has occurred'],
  ise: [200099, 'Our system experienced an error. Please try again later.'],
  npe: [200099, 'System threw a null or undefined error. This should not be a client issue'],
  env: [200099, 'system environment failed to validate. This failure should never be returned to the client'],
  dataMissing: [200099, 'Some required data not defined after cleaning'],
} as const)

export type ErrorCodeKey = keyof typeof errorCodes
```

and a `validation` method that uses `ErrorCodeKey` currently, unfortunately now I need to have 2 different apps that have different values for `errorCodes`, trying to figure out how I could generify, but also restrict this to the right error codes for the app. also those error codes are shipping in a downstream codebase, so I won't have access to them.


```ts
export function validateRequired<IN extends Input, OUT extends IN = IN>(
  object: IN | null | undefined,
  schema: Joi.AnySchema<OUT>,
  code: ErrorCodeKey = 'unknownJoi', // TODO: default should be removed
  options?: Joi.ValidationOptions,
): OUT {
  return requireNonNullish<OUT>(validateOptional<IN, OUT>(object, schema.required(), code, options))
}
```

**Comment by Beraliv** [comment]
@xenoterracide it would be good if you shared the link to Playground, so it would be clear what you're trying to do

**Comment by xenoterracide** [comment]
@Beraliv not sure this is going to help much [tsplayground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&ts=4.1.5&noPropertyAccessFromIndexSignature=true#code/JYWwDg9gTgLgBAbzgZQIYDMCmARYBjGYCAO1SgE8AaOABSlGEIDdM4BfOdKCEOAchgBnALSZBgzMUKoANoL4AoBXhKD4eKJlQxMAMVQFo5AOqMAFgGFVMKKmBS4AXgVxXcADxXia2-YB8ABQAlE5+Lm7uAKpwmAAeOsQAJoJwXj52xIFMsgCumABccJFBhdGOYW6VcNkyeQDcSjDkYKwAolDcUFaJmAAqOWAyrI5wAEpaiSQy5O4A2sQ5IABGmFDUPvYA5gD8ALphCnGQsHBNLXDtnd2YAJJJcU6IcLMA1oUbxJu7hZfQ1-2DVhsBRnNodP4QHopEbjVCTYjTdzjACOOWAmkS7jQWFwBCIpAo7l+XUhfQGQ3WNi2fhpShU3nUmm0mGJ12hcA0Wh0+kMFFMMEs1l8UiJ4JJUMCQSUR2g6msMTFbMenOZrNJggCCHCMgYMEKswAjAAGE0AJgAzLtKOFIsRgOhgJhElYQCBJHrnsaTQBOA1Wm0SKB3dAQfVeo3e03+1w5YgvYgQADuxAAUhBgPrTSbs9Q+Ci8mpqrJgIltPiFZ0+NG4AmYLoILHEpns0aDbn82IdIk4JpBA2oHhWLXOA2klXra4lnCO2pm9nTbmAILECvQOBmVApCB4PA5DpO8fhYASOcR725gDye7ggnIakwvCOq0dxEH3dQK9WnQAdLQhpvWBscg4FQTYMjgGRmSgb9D1cYgWlPb1z34ZA7x0XgBU0RMQJrHIZBkOA10bTAHWIJ1V2guBejMY8bzMBsZG7YcVhwvAdXdOBj0EPJYJiYgmEQ5C+Fve9H349ESDdBx0DsIZuxgCAix1UsdF-ajaJk4Bak0OiGKYzAWCgOAWM0GA9zI+TFIFVg2JfGBeJU1AAFkuK2QTc2QHhWE0VF0XIxyawgeAelI8iMB0Iy2K0O1PkPDhNw5awpQUAB6FKOQ-AQ4ETaAXhA4hyBAaBMGoJYcngEMoDdKBpmy3LyMqkCwDAA1UvSmUTlBC5FVJABpTBgJGF4BogdBTmaTBRootlGgmuA7jAcrHlaWI2JyHp3DoXVgBYagFnwuAAB84GI0Lu2O29lggGQ-COwilgAK0wAglEOWJjgq2M8RIJSS2ZfM-MxG4ADkYniSRknm+DyuoC9Il6MGEkhkHHhBwJwhqPJChR479oI47TvsJ0J0Snofh6np+vIBQSjgOGEa1VxTPMpS8hAlJ6bgNK4CKnSVHAHU8GZd8kjgSYxGILKyPIoW1AUYE2rF+0sE0BxUGag0e0wSA3o+xKGSalq1ShZUmR0Y2xE1cJY3jJNU3TU8TXbTBUU7X6VPLL9oF42t60bR2234Gcuy1vs90HQKKtHRJeKnRJg8dhd+GXCj1wS7dd33GPq2PApnizH0hKvIyRPQsGWnoSQ33yijfxof8JFOCgQLA+wIKgmDq3gvPZgLs8PLQh9TjMLCcLxwijMJiza6omiUkEei8KYoLjNYVAOXYhwuJ4-14pSek1CCBoaj+nQAYxAI+FQPhc27vhku5xJldWDj1bAU0tZ1jq5QNt-TQt9kKpzYU0tozE6cYEzJjTBmfOLYjTO1doWE+HsfpeygD7IKfskgBwQQWEOvZ+wR2HCGRssdpwuzwYnJcn4xRpy3DuPcGJeK53cvwYuN5B6Pnes+KuYUaE-j-FoRuQEW7gUghFTuJNu6sL4KhUSw9R7r3HkRe4Z0Z7qXnovRikdV6sU3vAbemA4rs31ofY+xYVKYHPk6S+19b4tHvgoIAA)

**Comment by xenoterracide** [comment]
how do you get those short urls anyways?

**Comment by xenoterracide** [comment]
p.s. (sorry about comment spam) we're using typescript 4.7.4

**Comment by xenoterracide** [comment]
Also, related, but tangential I've been trying to figure out why [this](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&noPropertyAccessFromIndexSignature=true#code/JYWwDg9gTgLgBAKQsOAzKERwOQCtnYBQokscA3nAApSjAzABuApnAL5oZbYwDOAtM169mAOwYBDADa8ihGAE8wrAJKiwAV3gBeOAFEAHgGMpGgCbMAPDToMWAGjiiNUqXAA+cDaIupgo5jMPOF4FEAAjCCkAPmCIcNxmIxhCVOYDUnhUb2TgCFE4RmlgMwkYZgAlZgBHDWAoQMs9CoqAeQqAYVaAET04dPKfXhCYWlEAc0cVADl+g0GzYbVNGEdWgFUAFTmFpdndGeiACkI4QoAuOBng51dg719-QPtTkKMAC2YQCUukYAA6ACCogUAGUPl8JJYNptoi8zkYIBZLs02p0enp4XAIGAGPleAB+X7If4ANWKpTxolauLyol4LwAlJcYRRXg0YBooAVGHAJMMYYQ2KkAPQiq5wMz5HhwADuEnEcBg72AwxgEDg-lQzCg+ha7S6vT5PhC7wgLjMohlJCkwCM9CkCjgHK5BQVTuYLCgjmVqtN5qkQXCrBd3P84xGY3GhER9Pg5p0hQpZUqNTqDTMR2wjGwjj+-3dR0Zjmw6mY2EZhAT-1QEAgQA) returns any, and if I can make the first (and only the first) generic required

**Comment by Beraliv** [comment]
> how do you get those short urls anyways?

I have a plugin in TS Playground
<img width="350" alt="Screenshot 2022-08-10 at 13 59 29" src="https://user-images.githubusercontent.com/2991847/183907414-66680de8-e308-4689-b5bf-46a1d018a0c2.png">

<img width="358" alt="Screenshot 2022-08-10 at 13 59 34" src="https://user-images.githubusercontent.com/2991847/183907434-8abda615-6103-41e8-8f82-cc6bd1e64ed3.png">

**Comment by Beraliv** [comment]
> @Beraliv not sure this is going to help much [tsplayground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&jsx=0&ts=4.1.5&noPropertyAccessFromIndexSignature=true#code/JYWwDg9gTgLgBAbzgZQIYDMCmARYBjGYCAO1SgE8AaOABSlGEIDdM4BfOdKCEOAchgBnALSZBgzMUKoANoL4AoBXhKD4eKJlQxMAMVQFo5AOqMAFgGFVMKKmBS4AXgVxXcADxXia2-YB8ABQAlE5+Lm7uAKpwmAAeOsQAJoJwXj52xIFMsgCumABccJFBhdGOYW6VcNkyeQDcSjDkYKwAolDcUFaJmAAqOWAyrI5wAEpaiSQy5O4A2sQ5IABGmFDUPvYA5gD8ALphCnGQsHBNLXDtnd2YAJJJcU6IcLMA1oUbxJu7hZfQ1-2DVhsBRnNodP4QHopEbjVCTYjTdzjACOOWAmkS7jQWFwBCIpAo7l+XUhfQGQ3WNi2fhpShU3nUmm0mGJ12hcA0Wh0+kMFFMMEs1l8UiJ4JJUMCQSUR2g6msMTFbMenOZrNJggCCHCMgYMEKswAjAAGE0AJgAzLtKOFIsRgOhgJhElYQCBJHrnsaTQBOA1Wm0SKB3dAQfVeo3e03+1w5YgvYgQADuxAAUhBgPrTSbs9Q+Ci8mpqrJgIltPiFZ0+NG4AmYLoILHEpns0aDbn82IdIk4JpBA2oHhWLXOA2klXra4lnCO2pm9nTbmAILECvQOBmVApCB4PA5DpO8fhYASOcR725gDye7ggnIakwvCOq0dxEH3dQK9WnQAdLQhpvWBscg4FQTYMjgGRmSgb9D1cYgWlPb1z34ZA7x0XgBU0RMQJrHIZBkOA10bTAHWIJ1V2guBejMY8bzMBsZG7YcVhwvAdXdOBj0EPJYJiYgmEQ5C+Fve9H349ESDdBx0DsIZuxgCAix1UsdF-ajaJk4Bak0OiGKYzAWCgOAWM0GA9zI+TFIFVg2JfGBeJU1AAFkuK2QTc2QHhWE0VF0XIxyawgeAelI8iMB0Iy2K0O1PkPDhNw5awpQUAB6FKOQ-AQ4ETaAXhA4hyBAaBMGoJYcngEMoDdKBpmy3LyMqkCwDAA1UvSmUTlBC5FVJABpTBgJGF4BogdBTmaTBRootlGgmuA7jAcrHlaWI2JyHp3DoXVgBYagFnwuAAB84GI0Lu2O29lggGQ-COwilgAK0wAglEOWJjgq2M8RIJSS2ZfM-MxG4ADkYniSRknm+DyuoC9Il6MGEkhkHHhBwJwhqPJChR479oI47TvsJ0J0Snofh6np+vIBQSjgOGEa1VxTPMpS8hAlJ6bgNK4CKnSVHAHU8GZd8kjgSYxGILKyPIoW1AUYE2rF+0sE0BxUGag0e0wSA3o+xKGSalq1ShZUmR0Y2xE1cJY3jJNU3TU8TXbTBUU7X6VPLL9oF42t60bR2234Gcuy1vs90HQKKtHRJeKnRJg8dhd+GXCj1wS7dd33GPq2PApnizH0hKvIyRPQsGWnoSQ33yijfxof8JFOCgQLA+wIKgmDq3gvPZgLs8PLQh9TjMLCcLxwijMJiza6omiUkEei8KYoLjNYVAOXYhwuJ4-14pSek1CCBoaj+nQAYxAI+FQPhc27vhku5xJldWDj1bAU0tZ1jq5QNt-TQt9kKpzYU0tozE6cYEzJjTBmfOLYjTO1doWE+HsfpeygD7IKfskgBwQQWEOvZ+wR2HCGRssdpwuzwYnJcn4xRpy3DuPcGJeK53cvwYuN5B6Pnes+KuYUaE-j-FoRuQEW7gUghFTuJNu6sL4KhUSw9R7r3HkRe4Z0Z7qXnovRikdV6sU3vAbemA4rs31ofY+xYVKYHPk6S+19b4tHvgoIAA)

That's working for me – https://tsplay.dev/wepMgW

Can you please prepare what was working before and not working now? It's not clear for me yet

**Comment by xenoterracide** [comment]
right, because that shows what was working before and what can't work now, this is if I remove the what was working before https://tsplay.dev/m048nm

**Comment by xenoterracide** [comment]
the best thing I've found is to take inspiration from the factory contstraint actually

```ts
export const validateOptionalImpl =
  <ERRORCODE extends string>(): Validator<ERRORCODE> =>
  <EC extends ERRORCODE, IN extends DefinedCanJson, OUT extends IN = IN>(
    v: IN | null | undefined,
    schema: Joi.AnySchema<unknown>,
    code: EC,
    options?: Joi.ValidationOptions,
  ) => {
    const args: ValidateArgs<ERRORCODE, IN> = { value: v, schema, code, options }
    const { value, error } = internalValidateImpl.validate<ERRORCODE, IN, OUT>(args)
    if (error != null) throw error
    return value
  }
  
  // and then
  
  const validateOptional = validateOptionalImpl<keyof typeof errorCodes>()

```

**Comment by Beraliv** [comment]
> the best thing I've found is to take inspiration from the factory contstraint actually
> 
> ```ts
> export const validateOptionalImpl =
>   <ERRORCODE extends string>(): Validator<ERRORCODE> =>
>   <EC extends ERRORCODE, IN extends DefinedCanJson, OUT extends IN = IN>(
>     v: IN | null | undefined,
>     schema: Joi.AnySchema<unknown>,
>     code: EC,
>     options?: Joi.ValidationOptions,
>   ) => {
>     const args: ValidateArgs<ERRORCODE, IN> = { value: v, schema, code, options }
>     const { value, error } = internalValidateImpl.validate<ERRORCODE, IN, OUT>(args)
>     if (error != null) throw error
>     return value
>   }
>   
>   // and then
>   
>   const validateOptional = validateOptionalImpl<keyof typeof errorCodes>()
> ```

Yeah, just generic types and constraints
