### ISSUE TITLE
add index access to dictionaries

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#316]
would it be possible to have

```ts
export type ErrorCodeKey = 'unknownJoi' | 'notFound' | 'badRequest' | 'ise' | 'npe' | 'dataMissing' | 'any.required'

SafeDictionary<[number, string], ErrorCodeKey>
```

behave like

```ts
export type ErrorCodeKey = 'unknownJoi' | 'notFound' | 'badRequest' | 'ise' | 'npe' | 'dataMissing' | 'any.required'

type ErrorCodeTuple = [number, string]

type ErrorCodeIndex = { [k: string]: ErrorCodeTuple }

export const errorCodes: SafeDictionary<ErrorCodeTuple, ErrorCodeKey> & ErrorCodeIndex 
```

or maybe add a new dictionary type?

**Comment by Beraliv** [comment]
Hey @xenoterracide!

Thank you for the suggestion!

Do I understand you right, that you want the autocompletion for `ErrorCodeKey` but still want to access other keys and get `ErrorCodeTuple`, right?

**Comment by Beraliv** [comment]
@xenoterracide is there anything we can do here? do we have any action point that we can convert to a PR?

**Comment by xenoterracide** [comment]
I'm going to say no for now, or perhaps, I forget... lol. I'll reopen if yes.
