### ISSUE TITLE
Array of strings to object of keys with type T

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#322]
I want to do something like this

```ts
myFun( ...strings[]): NewType<string> {...}

myFun('a', 'b') // { a: string, b: string }
```

looks like this has the how to https://stackoverflow.com/a/60863735/206466

In my case this seems to be what I want

```ts
type ToObject<T, V> = T extends infer Key ? (Key extends PropertyKey ? { [P in Key]: V | undefined } : never) : never

type ResponseData = { data: { [k: string]: string } } | undefined

async getSecrets<K extends string>(...secretPaths: readonly K[]): Promise<UnionToIntersection<ToObject<K, string>>> {...
}
```

although the cast at the very end is annoying
```ts
export class SecretsClient {
  constructor(private readonly axios: AxiosInstance, private readonly lockboxId: string) {}

  async getSecret(secretPath: string): Promise<string | undefined> {
    const response = await this.axios.get<ResponseData>(`/v1/${this.lockboxId}/${secretPath}`)
    const { data } = response
    return data?.data[secretPath]
  }

  async getSecrets<K extends string>(...secretPaths: readonly K[]): Promise<UnionToIntersection<ToObject<K, string>>> {
    const secrets = await Promise.all(secretPaths.map(path => this.getSecret(path)))
    return secrets.reduce((prev, curr, idx) => _.set(secretPaths[idx], curr, prev), {}) as ToObject<K, string>
  }
}
```

**Comment by xenoterracide** [comment]
@Beraliv would it be possible to add a generic type of `ArrayToObjectType`? or something?

**Comment by xenoterracide** [comment]
as this code that I wrote is black magic to me, and I don't yet understand it. Also, doesn't seem like a bad use case for this library.

**Comment by xenoterracide** [comment]
@Beraliv should the type here be changed to enhancement?

**Comment by Beraliv** [comment]
Hey @xenoterracide 

Sorry for the late response

I think the type that you need is `Record<TArr[number], string>` – https://tsplay.dev/WY4zzm

I doubt there's a need of this type in ts-essentials

**Comment by xenoterracide** [comment]
Although that compiles, autocompletion in the IDE isn't working, you should be able to do `response.` ctrl+space and have it suggest `a` or `b` given my original.

**Comment by xenoterracide** [comment]
but yes, if doing that was as simple as that I would say it's not needed, just doesn't seem to do *everything* I'm trying to do ;)

**Comment by Beraliv** [comment]
Let's close it for now

If you need a different behaviour like https://github.com/ts-essentials/ts-essentials/issues/316, let's discuss it there

Otherwise, don't hesitate to open another issue and discuss it there

**Comment by xenoterracide** [comment]
well, we can open another one, but the thing I like (and I know some tsessentials stuff says this) is that 

```ts
type ToObject<T, V> = T extends infer Key ? (Key extends PropertyKey ? { [P in Key]: V | undefined } : never) : never
```

supports auto completion when typing it out e.g `obj.test` can be auto completed via the IDE, whereas the more built in you suggested doesn't allow for that. it'll compile it, but it won't suggest it.
