### ISSUE TITLE
DeepWritable

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#328]
I'm not personally a fan of non immutable objects (asside from builders), however I have people whinging at me for enforcing it (which I will probably have to undo) but seems like it would be a good idea to be able to mass undo readonly.

**Comment by Beraliv** [comment]
Hey @xenoterracide!

It's already there – https://github.com/ts-essentials/ts-essentials/blob/master/lib/types.ts#L186-L204

Was done here – https://github.com/ts-essentials/ts-essentials/issues/13

It's mentioned in README – https://github.com/ts-essentials/ts-essentials#writable

Example in Playground – https://tsplay.dev/Nr46VW

**Comment by xenoterracide** [comment]
Sorry, don't know how I missed this
