### ISSUE TITLE
One Parameter Exact

### ISSUE THREAD

**Issue by xenoterracide** [ts-essentials/ts-essentials#341]
I find myself writing `Exact` like this a lot

```ts
Exact<StorefrontMenuProductOptions, StorefrontMenuProductOptions>
```

would it be possible to change the signature to be something like

```ts
type Exact<A, B=A>
```

So instead I could just write

```ts
Exact<StorefrontMenuProductOptions>
```

**Comment by Beraliv** [comment]
Hello @xenoterracide!

Can you please explain why you need it like that? Can you have one or two examples?

Otherwise I would just use:

```diff
- Exact<StorefrontMenuProductOptions, StorefrontMenuProductOptions>
+ StorefrontMenuProductOptions
```

**Comment by xenoterracide** [comment]
yeah that might be fine, I seem to recall being able to have objects that have fields that I wasn't wanting and pass them to things like this, but then I tried it and couldn't reproduce.
