### ISSUE TITLE
Bug: `DeepReadonly` is not idempotent on readonly arrays

### ISSUE THREAD

**Issue by polyipseity** [ts-essentials/ts-essentials#362]
### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript`                           | `5.0.2` |
| `ts-essentials`                        | `9.3.1` |

### Repro Code

```typescript
import type { DeepReadonly } from "ts-essentials"
export type Items = DeepReadonly<readonly ["item1", "item2"]>
```

### TypeScript Playground

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAIilYBKKAhgCYQB2ANonAL5wBmUEIcARDAM4C0KnnKcjGBFKnNgFgAUCgAekWAmRoAkjBQhOcALzZcBYmSqIAPFEMVqcANptg6kAEY2AGnb2NAJjYBdAHzSQA

### Expected Result

Type of `Items` should be `readonly ["item1", "item2"]`.

### Actual Result

Type of `Items` is actually `readonly ("item1" | "item2")[]`.

**Comment by polyipseity** [comment]
It looks like this can be fixed by changing `IsTuple`:
```ts
export declare type IsTuple<T> = T extends any[] ? (any[] extends T ? never : T) : never;
```
to
```ts
export declare type IsTuple<T> = T extends readonly any[] ? (any[] extends T ? never : T) : never;
```
Notice the extra `readonly` in the first tenary operator.

**Comment by Beraliv** [comment]
Hey @polyipseity!

Thank you so much for the contribution, I will have a look at it later today!
