### ISSUE TITLE
Enhancement: Check the compatibility with TypeScript 5.0

### ISSUE THREAD

**Issue by Beraliv** [ts-essentials/ts-essentials#365]
### What

I propose:

- to add TypeScript 5.0 CI check
- to document all differences if there are any
- to fix all broken tests when feasible
- to create bugs if required to fix issues separately

### Examples

No code examples required, as the change doesn't imply to add new type utility

### Additional Info

TS 5.0 beta – https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/

**Comment by viceice** [comment]
fails on typescript 5.2

- https://github.com/renovatebot/renovate/pull/24493

**Comment by Beraliv** [comment]
> fails on typescript 5.2
> 
> - https://github.com/renovatebot/renovate/pull/24493

Thank you for pinging me, I will start looking at the fix this week

**Comment by Beraliv** [comment]
@viceice I've started investigating issues with `CamelCase` in https://github.com/ts-essentials/ts-essentials/pull/377, I will let you know when it's solved

**Comment by Beraliv** [comment]
Merged in 9.4.1 - https://github.com/ts-essentials/ts-essentials/pull/378
