### ISSUE TITLE
Bug: [meta] TypeScript isn’t an optional peer dependency

### ISSUE THREAD

**Issue by kripod** [ts-essentials/ts-essentials#370]
### Versions

| package                                | version |
| -------------------------------------- | ------- |
| `typescript`                           | none |
| `ts-essentials`                        | `9.3.2` |

### Repro Code

```typescript
N/A
```

### TypeScript Playground

N/A

### Expected Result

When used within a library, ts-essentials expects a certain version of `typescript` to be installed as a peer dependency.

However, when a JS-only app using [pnpm](https://pnpm.io/) imports a library which depends on `ts-essentials`, pnpm will emit an error about a missing peer dependency – namely `typescript` – even though an app written in JS needn’t have TypeScript installed.

### Actual Result

While specifying a minimum version range is reasonable, TypeScript should be marked as optional peer dependency. Therefore, the range constraint would still apply but only when `typescript` itself is installed.

**Comment by Beraliv** [comment]
Hey @kripod!

Apologies for the late response and thank you for the suggestion!

Does it mean that I can set [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) and for npm (yarn, pnpm) versions that support it will skip the check and won't throw an error during install?

I'm happy to document it and include into README.md as a fix, however I will need to properly test it, do you know what would be the best way to do it?

Also as a workaround for pnpm, you can set [pnpm.packageExtensions](https://pnpm.io/package_json#pnpmpackageextensions) to fix it for now until the work is done on ts-essentials side

**Comment by kripod** [comment]
@Beraliv yeah, setting `peerDependenciesMeta[package].optional` to `true` means that the constraint for `package`’s version range is only enforced if `package` is installed.

The issue with `pnpm.packageExtensions` is that it only works directly within apps, but not for libraries which are consumed by apps. Even if I’d set `pnpm.packageExtensions` within a library of mine, the JavaScript apps which consume my library would need to do the same if `ts-essentials` is a dependency (or peer dependency) of my library.

All in all, in order to avoid having to install TypeScript within JavaScript apps just for the sake of satisfying the `peerDependencies` requirement of ts-essentials, my proposed `peerDependenciesMeta` options should be added directly within the `package.json` of ts-essentials.

**Comment by Beraliv** [comment]
It's released in https://github.com/ts-essentials/ts-essentials/releases/tag/v9.4.0
