### ISSUE TITLE
Enhancement: [PartialBy, RequiredBy]

### ISSUE THREAD

**Issue by szulcus** [ts-essentials/ts-essentials#376]
### What

I'm sorry if the library already has such types, but I can't find it anywhere. It seems to me that this is a fundamental thing that should be built into TypeScript.

### Examples

- PartialBy
```ts
type PartialBy<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

interface Example {
  prop1: string;
  prop2: number;
  prop3: boolean;
}

type PartialProps = PartialBy<Example, 'prop1' | 'prop2'>;

/*
{
  prop1?: string;
  prop2?: number;
  prop3: boolean;
}
*/
```
- RequiredBy
```ts
type RequiredBy<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>;

interface Example {
  prop1?: string;
  prop2?: number;
  prop3?: boolean;
}

type RequiredProps = RequiredBy<Example, 'prop1' | 'prop2'>;

/*
{
  prop1: string;
  prop2: number;
  prop3?: boolean;
}
*/
```

### Additional Info

https://stackoverflow.com/a/54178819

**Comment by Beraliv** [comment]
Hey @szulcus!

Thank you for your suggestions, but we already have several helpers that can create new types with updated properties: https://github.com/ts-essentials/ts-essentials#mark-wrapper-types, e.g.  [MarkOptional](https://github.com/ts-essentials/ts-essentials/tree/master/lib%2Fmark-optional) and [MarkRequired](https://github.com/ts-essentials/ts-essentials/blob/master/lib/mark-required)

Please let me know if this doesn't work for you

**Comment by szulcus** [comment]
@Beraliv This is what I was looking for. Thank you very much! ❤️
