### ISSUE TITLE
Enhancement: [Paths<Type>] Add configurable wildcard for matching array indices

### ISSUE THREAD

**Issue by mylesj** [ts-essentials/ts-essentials#411]
### What

I propose an addition to [`Paths<Type>`](https://github.com/ts-essentials/ts-essentials/tree/master/lib/paths) - specifically the [options](https://github.com/ts-essentials/ts-essentials/blob/d0ad79f3e022f9ac97b5ec08314a20d3286db9dc/lib/paths/index.ts#L25-L42) - that would allow for a more permissive wildcard with regard to array indices. For context I'm writing a generic _"search"_ utility for an object store in my project, and would like for my consumer to be able to differentiate their interest in a specific element from interest in all elements of the same set.

### Examples

```typescript
interface Company {
  name: string;
  employees: { name: string }[];
}

const path: Paths<Company, { wildcard: '*' }> = 'employees.*.name';
```

### Additional Info

Strictly speaking I can already work around this by using something like `-1` as my wildcard, however this is obscure to the reader - I'd prefer that my API is explicit and discoverable. 

```typescript
const path: Paths<Company> = 'employees.-1.name'; // satisfies TypeScript but not idiomatic
```

**Comment by Beraliv** [comment]
Hey @mylesj!

Thank you for raising an issue with your proposal!

I agree that adding an option to [options](https://github.com/ts-essentials/ts-essentials/blob/d0ad79f3e022f9ac97b5ec08314a20d3286db9dc/lib/paths/index.ts#L25-L42) would be the best place.

At the moment of reading, I have 2 concerns:

1. The name of the config option (i.e. `wildcard`) is too generic

When an engineer looks at `Paths<Company, { wildcard: '*' }>`, it's unclear what wildcard is used for:
- Will it use any object properties to find the matched path?
- Is it a specific shortcut to choose the first/last object property where the matched path exists?
- Is it something else?

I believe it will confuse engineers at first glance and may mislead them.

To help engineers, I suggest renaming `wildcard` to something else, e.g. `arrayIndexAccessor`, `arrayIndexWildcard`, etc. And then, for example, use `arrayIndexWildcard: '-1'` by default (it also keeps backwards compatibility) and you can override it to `arrayIndexWildcard: '*'` in your library.

What do you think?

2. Be cautious when setting the value to `*`

Although I agree that `'employees.*.name'` looks neater than `employees.-1.name`, without much context, it may still confuse engineers.

However, a utility type `Paths` will not be used for searching or finding matches (ex. 1 and ex. 2 in a concern 1) therefore I'm happy to keep `*` as an example of array index wildcard overrides in the `ts-essentials` docs

---

With regards to time, I won't be able to implement it this week. If you have some time, feel free to open a PR against ts-essentials and ping me, I will have time to review it.

**Comment by mylesj** [comment]
Awesome, thanks for the quick response. Regarding your concerns:

> 1. The name of the config option (i.e. wildcard) is too generic

For sure, I'm not attached to this naming - this was a conversation starter. Would `anyArrayIndexAccessor` be reasonable? This clarifies the intent to satisfy ***any*** array element.

> 2. Be cautious when setting the value to * [...] Although I agree that 'employees.*.name' looks neater than employees.-1.name, without much context, it may still confuse engineers.

Colloquially I think most engineers would intuit an asterisk as matching anything in that position, given how ubiquitous the character is in things like glob patterns. The likes of the "head" and "tail" of an array are better identified by `0` and `-1` for example (consistent with [`Array.prototype.at()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at) at the least).

In any case the proposal is opt-in so the meaning of symbols is left up to the application context / developer discretion.

--- 

> With regards to time, I won't be able to implement it this week. If you have some time, feel free to open a PR against ts-essentials and ping me, I will have time to review it.

No worries, I might need some help with it but an attempt was made...

**Comment by Beraliv** [comment]
This is not deployed yet, it will be a part of 10.0.3 - https://github.com/ts-essentials/ts-essentials/pull/410

**Comment by Beraliv** [comment]
@mylesj I'm planning to release 10.0.3 after this PR is completed - https://github.com/ts-essentials/ts-essentials/pull/416. It will be not later than this weekend

**Comment by mylesj** [comment]
Thanks for the heads up, much appreciated.

**Comment by Beraliv** [comment]
@mylesj the PR is merged so I'm making a release right now, so you can update the version in your project to `10.0.3`

**Comment by Beraliv** [comment]
@mylesj I just updated the list of contributors and [added you to the list](https://github.com/ts-essentials/ts-essentials?tab=readme-ov-file#contributors), thank you for your efforts once again!

**Comment by mylesj** [comment]
Thanks @Beraliv, likewise appreciate your efforts.
